/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.VHabitacion;
import Datos.VReserva;
import Logica.FHabitacion;
import Logica.FReserva;
import java.sql.Date;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fede
 */
public class FrmReserva extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmReserva
     */
    public FrmReserva() {
        initComponents();
        Mostrar("");
        Inhabilitar();
        
    }

    private String accion = "guardar";
    public static int idUsuario;
    
    void OcultarColumnas(){
        tablaListado.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaListado.getColumnModel().getColumn(0).setMinWidth(0);
        tablaListado.getColumnModel().getColumn(0).setPreferredWidth(0);
        
        tablaListado.getColumnModel().getColumn(1).setMaxWidth(0);
        tablaListado.getColumnModel().getColumn(1).setMinWidth(0);
        tablaListado.getColumnModel().getColumn(1).setPreferredWidth(0);
        
        tablaListado.getColumnModel().getColumn(3).setMaxWidth(0);
        tablaListado.getColumnModel().getColumn(3).setMinWidth(0);
        tablaListado.getColumnModel().getColumn(3).setPreferredWidth(0);
        
        tablaListado.getColumnModel().getColumn(5).setMaxWidth(0);
        tablaListado.getColumnModel().getColumn(5).setMinWidth(0);
        tablaListado.getColumnModel().getColumn(5).setPreferredWidth(0);
    }
    
    void Inhabilitar(){
        txtIdReserva.setVisible(false);
        txtIdHabitacion.setVisible(false);
        txtIdHabitacion.setEnabled(false);
        txtIdCliente.setEnabled(false);
        txtIdTrabajador.setEnabled(false);
        
        txtNumeroHabitacion.setEnabled(false);
        txtCliente.setEnabled(false);
        txtTrabajador.setEnabled(false);
        cboTipoReserva.setEnabled(false);
        DCFechaReserva.setEnabled(false);
        DCFechaIngreso.setEnabled(false);
        DCFechaSalida.setEnabled(false);
        txtCostoAlojamiento.setEnabled(false);
        cboTipoReserva.setEnabled(false);
        
        btnGuardar.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnBuscaHabitacion.setEnabled(false);
        btnBuscaCliente.setEnabled(false);
        
        txtIdReserva.setText("");
        txtIdCliente.setText("");
        txtNumeroHabitacion.setText("");
        txtCostoAlojamiento.setText("");
        txtIdHabitacion.setText("");
        
    }
    
    void Habilitar(){
        txtIdReserva.setVisible(false);
        txtIdHabitacion.setVisible(false);
        txtIdHabitacion.setEnabled(false);
        txtIdCliente.setEnabled(false);
        txtIdTrabajador.setEnabled(false);
        
        txtNumeroHabitacion.setEnabled(false);
        txtCliente.setEnabled(false);
        txtTrabajador.setEnabled(false);
        cboTipoReserva.setEnabled(true);
        DCFechaReserva.setEnabled(true);
        DCFechaIngreso.setEnabled(true);
        DCFechaSalida.setEnabled(true);
        txtCostoAlojamiento.setEnabled(true);
        cboTipoReserva.setEnabled(true);
        
        btnGuardar.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnBuscaHabitacion.setEnabled(true);
        btnBuscaCliente.setEnabled(true);
        
        txtIdReserva.setText("");
        txtIdCliente.setText("");
        txtNumeroHabitacion.setText("");
        txtCostoAlojamiento.setText("");
        txtIdHabitacion.setText("");
        
        
    }
    
    void Mostrar(String mostrar){
        try {
            DefaultTableModel modelo;
            FReserva func = new FReserva();
            modelo = func.mostrar(mostrar);
            
            tablaListado.setModel(modelo);
            OcultarColumnas();
            lblTotalRegistros.setText("Total Registros: " + Integer.toString(func.totalRegistros));
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, "Error en procedimiento 'Mostrar' de la clase FrmReserva " + e);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnRegistroDeHabitaciones = new javax.swing.JPanel();
        txtIdReserva = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        txtIdHabitacion = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        txtCostoAlojamiento = new javax.swing.JTextField();
        lblPrecioDiario = new javax.swing.JLabel();
        cboTipoReserva = new javax.swing.JComboBox<>();
        lblEstado = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtNumeroHabitacion = new javax.swing.JTextField();
        txtIdCliente = new javax.swing.JTextField();
        txtCliente = new javax.swing.JTextField();
        txtIdTrabajador = new javax.swing.JTextField();
        txtTrabajador = new javax.swing.JTextField();
        lblDescripcion1 = new javax.swing.JLabel();
        DCFechaReserva = new com.toedter.calendar.JDateChooser();
        DCFechaSalida = new com.toedter.calendar.JDateChooser();
        lblPrecioDiario1 = new javax.swing.JLabel();
        lblPrecioDiario2 = new javax.swing.JLabel();
        DCFechaIngreso = new com.toedter.calendar.JDateChooser();
        lblPrecioDiario3 = new javax.swing.JLabel();
        lblPrecioDiario4 = new javax.swing.JLabel();
        cboEstadoDeReserva = new javax.swing.JComboBox<>();
        btnBuscaHabitacion = new javax.swing.JButton();
        btnBuscaCliente = new javax.swing.JButton();
        lblHabitacion = new javax.swing.JLabel();
        pnListadoDeHabitaciones = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaListado = new javax.swing.JTable();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblTotalRegistros = new javax.swing.JLabel();
        btnMostrarConsumos = new javax.swing.JButton();
        btnRealizarPagos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnRegistroDeHabitaciones.setBackground(new java.awt.Color(255, 153, 51));
        pnRegistroDeHabitaciones.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro de Reservas"));

        lblNumero.setText("Habitación");

        txtIdHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdHabitacionActionPerformed(evt);
            }
        });

        lblDescripcion.setText("Cliente");

        txtCostoAlojamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoAlojamientoActionPerformed(evt);
            }
        });

        lblPrecioDiario.setText("Fecha Reserva");

        cboTipoReserva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reserva", "Alquiler" }));
        cboTipoReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTipoReservaActionPerformed(evt);
            }
        });

        lblEstado.setText("Tipo Reserva");

        btnNuevo.setBackground(new java.awt.Color(255, 153, 51));
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(255, 153, 51));
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 153, 51));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtNumeroHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroHabitacionActionPerformed(evt);
            }
        });

        txtIdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdClienteActionPerformed(evt);
            }
        });

        txtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActionPerformed(evt);
            }
        });

        txtIdTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdTrabajadorActionPerformed(evt);
            }
        });

        txtTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTrabajadorActionPerformed(evt);
            }
        });

        lblDescripcion1.setText("Trabajador");

        lblPrecioDiario1.setText("Fecha Ingreso");

        lblPrecioDiario2.setText("Fecha Salida");

        lblPrecioDiario3.setText("Costo");

        lblPrecioDiario4.setText("Estado de Reserva");

        cboEstadoDeReserva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alquiler", "Pagada", "Anulada" }));
        cboEstadoDeReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEstadoDeReservaActionPerformed(evt);
            }
        });

        btnBuscaHabitacion.setBackground(new java.awt.Color(255, 153, 51));
        btnBuscaHabitacion.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscaHabitacion.setText("Cancelar");
        btnBuscaHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaHabitacionActionPerformed(evt);
            }
        });

        btnBuscaCliente.setBackground(new java.awt.Color(255, 153, 51));
        btnBuscaCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscaCliente.setText("Cancelar");
        btnBuscaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnRegistroDeHabitacionesLayout = new javax.swing.GroupLayout(pnRegistroDeHabitaciones);
        pnRegistroDeHabitaciones.setLayout(pnRegistroDeHabitacionesLayout);
        pnRegistroDeHabitacionesLayout.setHorizontalGroup(
            pnRegistroDeHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRegistroDeHabitacionesLayout.createSequentialGroup()
                .addGroup(pnRegistroDeHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnRegistroDeHabitacionesLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btnNuevo)
                        .addGap(58, 58, 58)
                        .addComponent(btnGuardar)
                        .addGap(57, 57, 57)
                        .addComponent(btnCancelar))
                    .addGroup(pnRegistroDeHabitacionesLayout.createSequentialGroup()
                        .addGroup(pnRegistroDeHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPrecioDiario)
                            .addComponent(lblPrecioDiario1)
                            .addComponent(lblPrecioDiario2))
                        .addGap(18, 18, 18)
                        .addGroup(pnRegistroDeHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DCFechaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DCFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DCFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCostoAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboTipoReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 101, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnRegistroDeHabitacionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtIdReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
            .addGroup(pnRegistroDeHabitacionesLayout.createSequentialGroup()
                .addGroup(pnRegistroDeHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumero)
                    .addComponent(lblDescripcion)
                    .addComponent(lblDescripcion1))
                .addGap(27, 27, 27)
                .addGroup(pnRegistroDeHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnRegistroDeHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumeroHabitacion)
                    .addComponent(txtTrabajador)
                    .addComponent(txtCliente))
                .addGap(18, 18, 18)
                .addGroup(pnRegistroDeHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscaHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
            .addGroup(pnRegistroDeHabitacionesLayout.createSequentialGroup()
                .addGroup(pnRegistroDeHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEstado)
                    .addGroup(pnRegistroDeHabitacionesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnRegistroDeHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrecioDiario3)
                            .addGroup(pnRegistroDeHabitacionesLayout.createSequentialGroup()
                                .addComponent(lblPrecioDiario4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboEstadoDeReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnRegistroDeHabitacionesLayout.setVerticalGroup(
            pnRegistroDeHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRegistroDeHabitacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnRegistroDeHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnRegistroDeHabitacionesLayout.createSequentialGroup()
                        .addComponent(txtIdReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(pnRegistroDeHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNumero)
                            .addComponent(txtIdHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumeroHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscaHabitacion))
                        .addGap(18, 18, 18)
                        .addGroup(pnRegistroDeHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDescripcion)
                            .addComponent(btnBuscaCliente))
                        .addGap(18, 18, 18)
                        .addGroup(pnRegistroDeHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDescripcion1))
                        .addGap(18, 18, 18)
                        .addGroup(pnRegistroDeHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEstado)
                            .addComponent(cboTipoReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblPrecioDiario))
                    .addComponent(DCFechaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnRegistroDeHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrecioDiario1)
                    .addComponent(DCFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(pnRegistroDeHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPrecioDiario2)
                    .addComponent(DCFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnRegistroDeHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecioDiario3)
                    .addComponent(txtCostoAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnRegistroDeHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecioDiario4)
                    .addComponent(cboEstadoDeReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(pnRegistroDeHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar)
                    .addComponent(btnNuevo))
                .addGap(105, 105, 105))
        );

        lblHabitacion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHabitacion.setText("Reserva");

        pnListadoDeHabitaciones.setBackground(new java.awt.Color(255, 255, 102));
        pnListadoDeHabitaciones.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de reservas"));

        tablaListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaListado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaListadoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaListado);

        lblBuscar.setText("Buscar");

        btnBuscar.setBackground(new java.awt.Color(255, 255, 102));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 255, 102));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(255, 255, 102));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lblTotalRegistros.setText("Registros");

        btnMostrarConsumos.setText("Consumos");
        btnMostrarConsumos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarConsumosActionPerformed(evt);
            }
        });

        btnRealizarPagos.setText("Realizar Pagos");
        btnRealizarPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarPagosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnListadoDeHabitacionesLayout = new javax.swing.GroupLayout(pnListadoDeHabitaciones);
        pnListadoDeHabitaciones.setLayout(pnListadoDeHabitacionesLayout);
        pnListadoDeHabitacionesLayout.setHorizontalGroup(
            pnListadoDeHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(pnListadoDeHabitacionesLayout.createSequentialGroup()
                .addComponent(lblBuscar)
                .addGap(32, 32, 32)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalir)
                .addGap(0, 157, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnListadoDeHabitacionesLayout.createSequentialGroup()
                .addComponent(btnMostrarConsumos, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRealizarPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTotalRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnListadoDeHabitacionesLayout.setVerticalGroup(
            pnListadoDeHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnListadoDeHabitacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnListadoDeHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnEliminar)
                    .addComponent(btnSalir))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnListadoDeHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalRegistros)
                    .addGroup(pnListadoDeHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnMostrarConsumos)
                        .addComponent(btnRealizarPagos)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnRegistroDeHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnListadoDeHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHabitacion)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblHabitacion)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnListadoDeHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnRegistroDeHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdHabitacionActionPerformed
        // TODO add your handling code here:
        txtIdHabitacion.transferFocus();
    }//GEN-LAST:event_txtIdHabitacionActionPerformed

    private void txtCostoAlojamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoAlojamientoActionPerformed
        // TODO add your handling code here:
        txtCostoAlojamiento.transferFocus();
    }//GEN-LAST:event_txtCostoAlojamientoActionPerformed

    private void cboTipoReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoReservaActionPerformed
        // TODO add your handling code here:
        cboTipoReserva.transferFocus();
    }//GEN-LAST:event_cboTipoReservaActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        Habilitar();
        btnGuardar.setText("Guardar");
        accion = "Guardar";
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:

        if (txtIdHabitacion.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar una habitacion");
            txtIdHabitacion.requestFocus();
            return;
        }
        if (txtIdCliente.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar un cliente");
            txtIdCliente.requestFocus();
            return;
        }
        if (txtCostoAlojamiento.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar un costo de alojamiento");
            txtCostoAlojamiento.requestFocus();
            return;
        }

        VReserva dts = new VReserva();
        FReserva func = new FReserva();

        dts.setIdHabitacion(Integer.parseInt(txtIdHabitacion.getText()));
        dts.setIdCliente(Integer.parseInt(txtIdCliente.getText()));
        dts.setIdTrabajador(idUsuario);

        int seleccionado = cboTipoReserva.getSelectedIndex();
        dts.setTipoDeReserva((String)cboTipoReserva.getItemAt(seleccionado));
        
        Calendar cal;
        int d,m,a;
        cal = DCFechaReserva.getCalendar();
        d =  cal.get(Calendar.DAY_OF_MONTH);
        m =  cal.get(Calendar.MONTH);
        a =  cal.get(Calendar.YEAR) - 1900;
        dts.setFechaReserva(new Date(a,m,d));
        
        cal = DCFechaIngreso.getCalendar();
        d =  cal.get(Calendar.DAY_OF_MONTH);
        m =  cal.get(Calendar.MONTH);
        a =  cal.get(Calendar.YEAR) - 1900;
        dts.setFechaIngreso(new Date(a,m,d));
        
        cal = DCFechaSalida.getCalendar();
        d =  cal.get(Calendar.DAY_OF_MONTH);
        m =  cal.get(Calendar.MONTH);
        a =  cal.get(Calendar.YEAR) - 1900;
        dts.setFechaEgreso(new Date(a,m,d));
        
        dts.setCostoAlojamiento(Double.parseDouble(txtCostoAlojamiento.getText()));
        seleccionado = cboEstadoDeReserva.getSelectedIndex();
        dts.setEstado((String)cboEstadoDeReserva.getItemAt(seleccionado));

        try{
            if (accion.equalsIgnoreCase("Guardar")) {
                if (func.Insertar(dts)) {
                    JOptionPane.showMessageDialog(rootPane, "La reserva fué registrada satisfactoriamente.");
                    Mostrar("");
                    Inhabilitar();
                    
                    //Ocupamos la habitacion alquilada
                    FHabitacion func3 = new FHabitacion();
                    VHabitacion dts3  =  new VHabitacion();
                    
                    dts3.setIdHabitacion(Integer.parseInt(txtIdHabitacion.getText()));
                    func3.Ocupar(dts3);
                }
            }else if (accion.equalsIgnoreCase("editar")) {
                dts.setIdReserva(Integer.parseInt(txtIdReserva.getText()));
                dts.setIdTrabajador(Integer.parseInt(txtIdTrabajador.getText()));

                if (func.Editar(dts)) {
                    JOptionPane.showMessageDialog(rootPane, "La reserva fué editada satisfactoriamente.");
                    Mostrar("");
                    Inhabilitar();

                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Ocurrio un error  en el metodo btnGuardarActionPerformed de la clase FrmReserva: " + e);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tablaListadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaListadoMouseClicked
        // TODO add your handling code here:

        try{
            btnGuardar.setText("Editar");
            Habilitar();
            btnEliminar.setEnabled(true);
            accion = "Editar";

            int fila = tablaListado.rowAtPoint(evt.getPoint());

            txtIdReserva.setText(tablaListado.getValueAt(fila, 0).toString());
            txtIdHabitacion.setText(tablaListado.getValueAt(fila, 1).toString());
            txtNumeroHabitacion.setText(tablaListado.getValueAt(fila, 2).toString());
            txtIdCliente.setText(tablaListado.getValueAt(fila, 3).toString());
            txtCliente.setText(tablaListado.getValueAt(fila, 4).toString());
            txtIdTrabajador.setText(tablaListado.getValueAt(fila, 5).toString());
            txtTrabajador.setText(tablaListado.getValueAt(fila, 6).toString());
            cboTipoReserva.setSelectedItem(tablaListado.getValueAt(fila, 7).toString());
            DCFechaReserva.setDate(Date.valueOf(tablaListado.getValueAt(fila, 8).toString()));
            DCFechaIngreso.setDate(Date.valueOf(tablaListado.getValueAt(fila, 9).toString()));
            DCFechaSalida.setDate(Date.valueOf(tablaListado.getValueAt(fila, 10).toString()));
            txtCostoAlojamiento.setText(tablaListado.getValueAt(fila, 11).toString());
            cboEstadoDeReserva.setSelectedItem(tablaListado.getValueAt(fila, 12).toString());
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Ocurrió un error inesperado en el metodo tablaListadoMouseClicked de la clase FrmReserva: " + e);
        }
    }//GEN-LAST:event_tablaListadoMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        Mostrar(txtBuscar.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        try{
            if (!txtIdReserva.getText().equalsIgnoreCase("")) {
                int confirmacion = JOptionPane.showConfirmDialog(rootPane, "¿Estás seguro de que quieres eliminar la reserva?", "Confirmar", 2);

                if (confirmacion == 0) {
                    FReserva func = new FReserva();
                    VReserva dts = new VReserva();

                    dts.setIdReserva(Integer.parseInt(txtIdReserva.getText()));
                    func.Eliminar(dts);
                    Mostrar("");
                    Inhabilitar();
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Amigo, tienes un error aquí => " + e);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtNumeroHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroHabitacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroHabitacionActionPerformed

    private void txtIdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdClienteActionPerformed

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActionPerformed

    private void txtIdTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdTrabajadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdTrabajadorActionPerformed

    private void txtTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTrabajadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTrabajadorActionPerformed

    private void cboEstadoDeReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEstadoDeReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboEstadoDeReservaActionPerformed

    private void btnBuscaHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaHabitacionActionPerformed
        // TODO add your handling code here:
        FrmVistaHabitacion form = new FrmVistaHabitacion();
        form.toFront();
        form.setVisible(true);
        
    }//GEN-LAST:event_btnBuscaHabitacionActionPerformed

    private void btnBuscaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaClienteActionPerformed
        // TODO add your handling code here:
        FrmVistaCliente form = new FrmVistaCliente();
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_btnBuscaClienteActionPerformed

    private void btnMostrarConsumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarConsumosActionPerformed
        // TODO add your handling code here:
        int fila = tablaListado.getSelectedRow();
        FrmConsumo.idReserva = tablaListado.getValueAt(fila, 0).toString();
        FrmConsumo.cliente = tablaListado.getValueAt(fila, 4).toString();
        
        FrmConsumo form = new FrmConsumo();
        FrmInicio.Escritorio.add(form);
        form.toFront();
        form.setVisible(true);
        
    }//GEN-LAST:event_btnMostrarConsumosActionPerformed

    private void btnRealizarPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarPagosActionPerformed
        // TODO add your handling code here:
        int fila = tablaListado.getSelectedRow();
        FrmPago.idReserva = tablaListado.getValueAt(fila, 0).toString();
        FrmPago.cliente = tablaListado.getValueAt(fila, 4).toString();
        FrmPago.totalReserva = Double.parseDouble(tablaListado.getValueAt(fila, 11).toString());
        FrmPago.idHabitacion = tablaListado.getValueAt(fila, 1).toString();
        FrmPago.habitacion = tablaListado.getValueAt(fila, 2).toString();
        
        FrmPago form = new FrmPago();
        FrmInicio.Escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_btnRealizarPagosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmReserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DCFechaIngreso;
    private com.toedter.calendar.JDateChooser DCFechaReserva;
    private com.toedter.calendar.JDateChooser DCFechaSalida;
    private javax.swing.JButton btnBuscaCliente;
    private javax.swing.JButton btnBuscaHabitacion;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMostrarConsumos;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRealizarPagos;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cboEstadoDeReserva;
    private javax.swing.JComboBox<String> cboTipoReserva;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblDescripcion1;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblHabitacion;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblPrecioDiario;
    private javax.swing.JLabel lblPrecioDiario1;
    private javax.swing.JLabel lblPrecioDiario2;
    private javax.swing.JLabel lblPrecioDiario3;
    private javax.swing.JLabel lblPrecioDiario4;
    private javax.swing.JLabel lblTotalRegistros;
    private javax.swing.JPanel pnListadoDeHabitaciones;
    private javax.swing.JPanel pnRegistroDeHabitaciones;
    private javax.swing.JTable tablaListado;
    private javax.swing.JTextField txtBuscar;
    public static javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtCostoAlojamiento;
    public static javax.swing.JTextField txtIdCliente;
    public static javax.swing.JTextField txtIdHabitacion;
    private javax.swing.JTextField txtIdReserva;
    public static javax.swing.JTextField txtIdTrabajador;
    public static javax.swing.JTextField txtNumeroHabitacion;
    public static javax.swing.JTextField txtTrabajador;
    // End of variables declaration//GEN-END:variables
}
